# Generated by Django 5.1.4 on 2024-12-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
